### ISSUE TITLE
Build errors for twig files

### ISSUE THREAD

**Issue by selwynpolit** [selwynpolit/studyguide#14]
Actions is showing a third step "pages  build and deployment" which fails when it encounters some twig.  Even though this is using the same workflow setup as Drupal At your Fingertips. It does seem to actually build correctly but I'm quite confused by this.

![image](https://github.com/user-attachments/assets/1a23c70a-d04d-4e08-8ea9-84369907ef2b)

**Comment by maks-oleksyuk** [comment]
@selwynpolit, you need to change the deployment settings to a custom action.

`Repo` -> `Settings` -> `Pages` -> `Build and deployment` -> `Source` -> `GitHub Action`.

This should disable the standard page deployment process.

**Comment by selwynpolit** [comment]
Thanks @maks-oleksyuk - great troubleshooting as always!  What do you think of the study guide?

**Comment by maks-oleksyuk** [comment]
> Thanks @maks-oleksyuk - great troubleshooting as always! What do you think of the study guide?

This will be a great guide, and it's good that it's already in process (not an idea). I will help write it or improve it as I have time.
